#!/usr/bin/env node
// Bankiersgrün design system tooling. The source lives in design-system/ (bundle.js is a
// hand-written classic script, no build step); only tokens.css is generated from tokens.json.
//
//   npm run ds:tokens            # regenerate design-system/tokens.css
//   npm run ds:tokens -- --check # fail if tokens.css is stale (CI runs this via the tests)

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export const NAMESPACE = 'Bankiersgruen';
export const DS_DIR = join(resolve(dirname(fileURLToPath(import.meta.url)), '..'), 'design-system');

const ALIAS = /^\{([A-Za-z0-9][A-Za-z0-9_.-]*)\}$/;

function cssValue(value) {
  const m = typeof value === 'string' && value.match(ALIAS);
  return m ? `var(--${m[1]})` : String(value);
}

/** tokens.json → CSS: first theme in :root, further themes as [data-theme="<id>"], type styles as .t-<name>. */
export function tokensToCss(tokens) {
  const themes = tokens.color?.themes ?? [];
  const base = themes[0]?.id;
  const rootLines = [];
  const themeLines = Object.fromEntries(themes.slice(1).map((t) => [t.id, []]));

  for (const t of tokens.color?.tokens ?? []) {
    if (typeof t.value === 'string') {
      rootLines.push(`  --${t.name}: ${cssValue(t.value)};`);
      continue;
    }
    rootLines.push(`  --${t.name}: ${cssValue(t.value[base])};`);
    for (const id of Object.keys(themeLines)) {
      if (t.value[id] !== undefined) themeLines[id].push(`  --${t.name}: ${cssValue(t.value[id])};`);
    }
  }

  for (const [name, family] of Object.entries(tokens.type?.families ?? {})) {
    rootLines.push(`  --font-${name}: ${family};`);
  }

  for (const [family, group] of Object.entries(tokens)) {
    if (family === 'color' || family === 'type' || !Array.isArray(group?.tokens)) continue;
    for (const t of group.tokens) rootLines.push(`  --${t.name}: ${cssValue(t.value)};`);
  }

  const typeRules = [];
  for (const group of tokens.type?.groups ?? []) {
    for (const s of group.styles) {
      const decl = [
        `font-family: var(--font-${group.family})`,
        `font-size: ${s.fontSize}`,
        `line-height: ${s.lineHeight}`,
        `font-weight: ${s.fontWeight}`,
      ];
      if (s.letterSpacing) decl.push(`letter-spacing: ${s.letterSpacing}`);
      if (s.name === 'label') decl.push('text-transform: uppercase');
      typeRules.push(`.t-${s.name} { ${decl.join('; ')}; }`);
    }
  }

  const blocks = [
    `/* GENERATED by scripts/design-system.mjs from tokens.json – do not edit. */`,
    `:root {\n  color-scheme: dark;\n${rootLines.join('\n')}\n}`,
    ...Object.entries(themeLines).map(([id, lines]) => `[data-theme="${id}"] {\n${lines.join('\n')}\n}`),
    `/* Type styles */\n${typeRules.join('\n')}`,
  ];
  return blocks.join('\n\n') + '\n';
}

export function expectedTokensCss(dir = DS_DIR) {
  return tokensToCss(JSON.parse(readFileSync(join(dir, 'tokens.json'), 'utf8')));
}

function main() {
  const check = process.argv.includes('--check');
  const target = join(DS_DIR, 'tokens.css');
  const css = expectedTokensCss();
  if (check) {
    if (readFileSync(target, 'utf8') !== css) {
      console.error('ds:tokens: design-system/tokens.css is stale – run `npm run ds:tokens`');
      process.exit(1);
    }
    console.log('ds:tokens: tokens.css is up to date');
    return;
  }
  writeFileSync(target, css);
  console.log('ds:tokens: design-system/tokens.css written');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
